---
creation_rules:
  - path_regex: .*\.sops\.env
    # Personal, VyOS
    key_groups:
      - age:
          - age14kzxlxcu3fj8xccwwf449prrmcawum0qth7jruwdfvlad4nwkv8stvgnx0
        pgp:
          - DA8002060402EC39B195451D5CED80362B5A4EF2
